[package]
name = "scone_cli"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
time = "*"
clap =  { version = "3.0.14", features = ["derive"] }
serde = { version = "*", features = ["derive"] }
serde_json = "*"
tinytemplate = "*"
clap-verbosity-flag = "*"
env_logger = "*"
log = "*"
json = "*"
handlebars = "*"
data-encoding = "*"
rand = "*"
shells = "*"
