[package]
name = "scone_cli"
version = "3.1.4"
edition = "2024"
publish = false
license = "Unlicense"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
log = "0.4.29"
spawn_server = { version = "2.1.2", git = "https://github.com/scontain/spawn_server.git", rev = "99bdf40a1b5e4d2902cef1e1df668b26c0382071" }
anyhow = "1.0"
semver = "1"
tempfile = "3"
