[package]
name = "scone_cli"
version = "3.0.0"
edition = "2024"
publish = false
license = "Unlicense"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
log = "0.4.29"
spawn_server = { version = "2.0.0", git = "https://github.com/scontain/spawn_server.git", rev = "f91b8e0f0db272f6595ed9a4d23e14a2d82d6d27" }
