[package]
name = "scone_cli"
version = "3.0.1"
edition = "2024"
publish = false
license = "Unlicense"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
log = "0.4.29"
spawn_server = { version = "2.1.0", git = "https://github.com/scontain/spawn_server.git", rev = "f4e506d7e59a77378d53eb50cdfacce696aae87a" }
