[package]
name = "scone_cli"
version = "0.1.1"
edition = "2024"
publish = false
license = "Unlicense"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde = { version = "*", features = ["derive"] }
serde_json = "*"
log = "*"
handlebars = "*"
rand = ">=0.9.0"
shells = "*"
opg = "*"
#get_if_addrs = "0.5.3"
once_cell = "*"
signpolicy = { version = "*", git = "https://github.com/scontain/signpolicy.git" }
