[package]
name = "scone_cli"
version = "0.1.0"
edition = "2021"
publish = false

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde = { version = "*", features = ["derive"] }
serde_json = "*"
log = "*"
handlebars = "*"
rand = "*"
shells = "*"
opg = "*"
#get_if_addrs = "0.5.3"
once_cell = "*"
signpolicy = { version = "*", git = "https://github.com/scontain/signpolicy.git" }
