[package]
name = "scone_cli"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
time = "0.1.25"
clap =  { version = "3.0.14", features = ["derive"] }
serde = { version = "*", features = ["derive"] }
serde_json = "1.0"
tinytemplate = "1.1"
clap-verbosity-flag = "*"
env_logger = "*"
log = "*"
json = "*"
handlebars = "*"
data-encoding = "*"
rand = "*"
shells = "*"
